### ISSUE TITLE
Add support for multiple values resolution

### ISSUE THREAD

**Issue by kilianc** [ljharb/util.promisify#10]
```js
const util = require('util');
const exec = util.promisify(require('child_process').exec);

async function lsExample() {
  const { stdout, stderr } = await exec('ls');
  console.log('stdout:', stdout);
  console.log('stderr:', stderr);
}
lsExample();
```

It is my understanding that the above [example](https://nodejs.org/dist/latest-v8.x/docs/api/child_process.html#child_process_child_process_exec_command_options_callback) does not work.

**Comment by ljharb** [comment]
Is it supposed to work with `util.promisify`?

`exec` might indeed have its own custom promisify implementation, which allows it to return both values, but absent one, it will (correctly) only give you a promise for `stdout`.

**Comment by kilianc** [comment]
Yeah, I feel you, but at the same time, I landed here when looking for a full polyfill and the first thing I tried didn't work lol.

I figured it would have been a good thing to share the unexpected behavior. Not sure how to approach it, maybe just a disclaimer in the README would be enough?

**Comment by ljharb** [comment]
A disclaimer in the readme that this package does not attempt to shim all of the custom promisify implementations in core would be fine. See #4 for more info.
