### ISSUE TITLE
Too many dependencies :(

### ISSUE THREAD

**Issue by Raynos** [ljharb/util.promisify#14]
```
│   ├─┬ util.promisify@1.0.0
│   │ ├─┬ define-properties@1.1.3
│   │ │ └── object-keys@1.1.1
│   │ └─┬ object.getownpropertydescriptors@2.0.3
│   │   ├── define-properties@1.1.3 deduped
│   │   └─┬ es-abstract@1.16.2
│   │     ├─┬ es-to-primitive@1.2.1
│   │     │ ├── is-callable@1.1.4 deduped
│   │     │ ├── is-date-object@1.0.1
│   │     │ └─┬ is-symbol@1.0.3
│   │     │   └── has-symbols@1.0.1 deduped
│   │     ├── function-bind@1.1.1
│   │     ├─┬ has@1.0.3
│   │     │ └── function-bind@1.1.1 deduped
│   │     ├── has-symbols@1.0.1
│   │     ├── is-callable@1.1.4
│   │     ├─┬ is-regex@1.0.4
│   │     │ └── has@1.0.3 deduped
│   │     ├── object-inspect@1.7.0
│   │     ├── object-keys@1.1.1 deduped
│   │     ├─┬ string.prototype.trimleft@2.1.0
│   │     │ ├── define-properties@1.1.3 deduped
│   │     │ └── function-bind@1.1.1 deduped
│   │     └─┬ string.prototype.trimright@2.1.0
│   │       ├── define-properties@1.1.3 deduped
│   │       └── function-bind@1.1.1 deduped
```

This seems massively overkill for `util.promisify` which already depends on ES5 and `global.Promise` ; 

We should be able to remove all these dependencies and make this a lightweight module.

**Comment by ljharb** [comment]
I’m not sure why dependency count matters; Object.getOwnPropertyDescriptors in particular isn’t something that can be removed.

**Comment by Raynos** [comment]
My current motivation is reducing dependencies that I have to manually audit for my production application.

Here is an extract from my production application

```
logs@1.0.0 /home/raynos/optoolco/logs
├── @optoolco/components@7.2.3
├── @optoolco/tonic@10.2.3
├─┬ aws-sdk@2.580.0
│ ├─┬ buffer@4.9.2
│ │ ├── base64-js@1.3.1
│ │ ├── ieee754@1.1.13 deduped
│ │ └── isarray@1.0.0
│ ├── events@1.1.1
│ ├── ieee754@1.1.13
│ ├── jmespath@0.15.0
│ ├── querystring@0.2.0
│ ├── sax@1.2.4
│ ├─┬ url@0.10.3
│ │ ├── punycode@1.3.2
│ │ └── querystring@0.2.0 deduped
│ ├── uuid@3.3.3
│ └─┬ xml2js@0.4.22
│   ├── sax@1.2.4 deduped
│   ├─┬ util.promisify@1.0.0
│   │ ├─┬ define-properties@1.1.3
│   │ │ └── object-keys@1.1.1
│   │ └─┬ object.getownpropertydescriptors@2.0.3
│   │   ├── define-properties@1.1.3 deduped
│   │   └─┬ es-abstract@1.16.2
│   │     ├─┬ es-to-primitive@1.2.1
│   │     │ ├── is-callable@1.1.4 deduped
│   │     │ ├── is-date-object@1.0.1
│   │     │ └─┬ is-symbol@1.0.3
│   │     │   └── has-symbols@1.0.1 deduped
│   │     ├── function-bind@1.1.1
│   │     ├─┬ has@1.0.3
│   │     │ └── function-bind@1.1.1 deduped
│   │     ├── has-symbols@1.0.1
│   │     ├── is-callable@1.1.4
│   │     ├─┬ is-regex@1.0.4
│   │     │ └── has@1.0.3 deduped
│   │     ├── object-inspect@1.7.0
│   │     ├── object-keys@1.1.1 deduped
│   │     ├─┬ string.prototype.trimleft@2.1.0
│   │     │ ├── define-properties@1.1.3 deduped
│   │     │ └── function-bind@1.1.1 deduped
│   │     └─┬ string.prototype.trimright@2.1.0
│   │       ├── define-properties@1.1.3 deduped
│   │       └── function-bind@1.1.1 deduped
│   └── xmlbuilder@11.0.1
├── ini@1.3.5
├─┬ leveldown@5.4.1
│ ├─┬ abstract-leveldown@6.2.2
│ │ ├── level-concat-iterator@2.0.1
│ │ ├─┬ level-supports@1.0.1
│ │ │ └── xtend@4.0.2 deduped
│ │ └── xtend@4.0.2
│ ├── napi-macros@2.0.0
│ └── node-gyp-build@4.1.1
├─┬ mkdirp@0.5.1
│ └── minimist@0.0.8
└── qs@1.0.0 (github:heapwolf/qs#38495eb5ff3da967a28f20d8ecb81518e4ae9c3c)
```

From this list the major dependencies I have to audit are `leveldown`, `aws-sdk`  `mkdirp` & `ini` .

I've read the source code all of all those except `aws-sdk` & `leveldown` ;

For `aws-sdk` I am happy to delegate the source code correctness checking itself to Amazon but I still want to audit it's transitive dependencies.

For `leveldown` I am still reading the dependencies & implementation.

To simplify auditing `aws-sdk` i'd be happy to reduce the total number of dependencies, I just audited `util.promisify` itself in passing making the following PR and am happy with the implementation :)

https://github.com/ljharb/util.promisify/pull/15

**Comment by Raynos** [comment]
For more information about 

> I’m not sure why dependency count matters; 

I recently tweeted about this issue https://twitter.com/Raynos/status/1207637549910507520

I was thinking of expanding my thoughts in a blog post about this topic.

**Comment by ljharb** [comment]
Bundling doesn’t reduce auditing burden, it increases it. More deps is better imo.

**Comment by ljharb** [comment]
In this case, every single one of those transitive deps is a package i maintain, ftr.

**Comment by Raynos** [comment]
> Bundling doesn’t reduce auditing burden, it increases it. More deps is better imo.

You would be correct if inlining was not trivial, it's <20 lines of code for 3 dependencies.

**Comment by ljharb** [comment]
The line count isn’t the issue; being able to delegate trust and testing responsibility, at all parts of the process, is important. For example, it shouldn’t take much to be able to implicitly trust everything in the inspect-js org (which i maintain), and then you never need to audit those lines of code again.

**Comment by Raynos** [comment]
@ljharb I trust you but that does not make you super man. I trust that your not going to add `postinstall: rm -rf ~` but i should still read the source code. 

For this particular use case I have upstream shares my point of view https://github.com/Leonidas-from-XIV/node-xml2js/pull/546 so my need is resolved.

**Comment by ljharb** [comment]
Fair enough.
