### ISSUE TITLE
shim.js: duplicate code?

### ISSUE THREAD

**Issue by rauschma** [ljharb/util.promisify#3]
Delete the first of the following two lines?

```js
util.promisify = polyfill;
Object.defineProperty(util, 'promisify', { value: polyfill });
```

**Comment by ljharb** [comment]
I intentionally did both - the former will only fail if it's non-writable, and there are some engines where you need normal assignment to be able to override things.

However, as I complete #1, I'll probably clean this up if I find it to be unnecessary.

**Comment by rauschma** [comment]
Interesting, thanks for the explanation! If the former fails, you get an exception, though (strict mode). Also intended?

Maybe add a comment so that people know that the duplication is intentional?

**Comment by ljharb** [comment]
ha, that's a good point that I explicitly put it in strict mode :-p

Yeah, I'll just remove this.
